name: CMake Build and test

on:
  push:
    branches: [ "*" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare ubuntu
      run: |
        chmod +x ./dep-ubuntu.sh && ./dep-ubuntu.sh \
        git config --global user.name "" \
        git config --global user.email ""

    - name: Run script to Build and Test
      run: |
        chmod +x ./auto-run.sh && ./auto-run.sh
