name: CMake Build and test

on:
  push:
    branches: [ "*" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare ubuntu
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y build-essential make cmake clang libsdl2-dev

    - name: Build and run manual tests
      run: |
        chmod +x ./compile.sh
        ./compile.sh manual_tests.cpp
        ./build/ga.out

    - name: Build and run final project
      run: |
        chmod +x ./compile.sh
        ./compile.sh main.cpp
        ./build/ga.out

    - name: Test
      working-directory: ./build
      run: ctest -V
